- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
- name: Configure fail2ban
  template:
    src: ../templates/fail2ban.conf.j2
    dest: /etc/fail2ban/jail.conf
- name: Restart fail2ban service
  service:
    name: fail2ban
    state: restarted
