apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:YOUR_ORG/infra.git
    targetRevision: main
    path: gitops/base/cluster-autoscaler
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
