apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-access
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:YOUR_ORG/infra.git
    targetRevision: main
    path: gitops/base/db-access
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
